# Use H2 in-memory database for tests
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate settings for tests
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# Keys JWT
application.security.jwt.SECRET_KEY=44d287b7ee4ad66875f28ee32b64b7ab5448901f36800fbaf3b6216d4479270c
application.security.jwt.EXPIRATION=86400000
