package org.test.backendprojecty.entity;

public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    FOCUS_ROOM_INVITE,
    COURSE_COMPLETED,
    STREAK_MILESTONE,
    TASK_REMINDER,
    FOCUS_ROOM_REPORT_READY,
    COURSE_INVITE,
    SUMMARY_READY,
    QUIZ_READY,
    SUMMARY_SHARED,
    QUIZ_SHARED
}
